version: 2.1

orbs: 
    node: circleci/node@5.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.14.0
    steps:
        - checkout
        - node/install-packages
        - run:
            name: Run tests
            command: npm run test-ci
      
workflows:
  run-tests:
    jobs:
      - build-and-test